get_workflow.ipynb
Adds a first example of interaction with the Workflow Hub as a Jupyter notebook.
=> Workflow Hub interaction example

check_nextflow.py, data/crates/ro-crate-nf-basic/test/params.cfg, data/crates/ro-crate-nf-basic/test/params.txt, ro_crate_test.ipynb
Adds a testing example on the minimal RO-Crate added with #2.
=> Nextflow crate test

examples/cwl/base_freq_sum/workflows/base_freq_sum_tests.yml, examples/cwl/base_freq_sum/workflows/run_planemo_tests.sh
Adds a planemo test file to the CWL example.
=> Add Planemo tests to the CWL example

docker-compose-template.yml
I had to add this in order to make lm see the database.
=> compose file: add POSTGRESQL_HOST env setting to lm

.travis.yml, lifemonitor/api/models.py, lifemonitor/auth/controllers.py, lifemonitor/auth/models.py, lifemonitor/auth/oauth2/__init__.py, lifemonitor/auth/oauth2/client/providers/seek.py, lifemonitor/auth/oauth2/client/services.py, lifemonitor/auth/oauth2/server/models.py, lifemonitor/utils.py, run.py, setup.cfg
Adds a Travis configuration file with flake8 and openapi-spec-validator linting as a start.
(a reboot of #24 after feedback)
=> CI support

interaction_experiments/check_cwl.py, interaction_experiments/check_galaxy.py, lifemonitor/api/models.py, lifemonitor/api/services.py, lifemonitor/ro_crate.py, lifemonitor/test_metadata.py, lifemonitor/utils.py
Integrates tools from the `test_metadata` and `ro_crate` modules into the API implementation.
=> Integrate test metadata tools

specs/api.yaml
=> Update API docs

Makefile
=> Fix generation of certs and keys

Makefile
=> Fix missing help on 'clean' command

README.md, examples/2_WorkflowRegistryAuthorize.ipynb, examples/3_WorkflowRegistryUsers.ipynb, examples/4_WorkflowRegistryWorkflows.ipynb
Updates the readme and the Jupyter notebook examples according to the recent changes in the API.
=> Update docs and examples

Makefile
* Fixes a problem with ro-crate generation as the current user
* Fixes some Emacs complaints about whitespace
=> Makefile: minor fixes

index.md, lm_admin_guide.md
=> Add docs from the README

README.md
Add an `acknowledgements` section to the README citing EOSC-Life, CRS4 and BBMRI-ERIC.
=> Add funding acknowledgements to README.md

index.md
* Documentation section to highlight the most important pages for quick reference
* Acknowledgments logos: improved alignment and added links to the relevant pages
* More links to external pages (e.g., Jenkins web site)
=> Landing page update

lifemonitor/api/controllers.py, lifemonitor/api/models/rocrate.py, lifemonitor/auth/oauth2/server/utils.py, lifemonitor/exceptions.py, lifemonitor/routes.py, lifemonitor/utils.py
This PR improves some of the error reporting, particularly in the code that imports RO-crates.  With these changes we have specific errors pointing the user to RO-crate download or processing problems.
=> Improve error reporting

lifemonitor/api/models/services/jenkins.py, lifemonitor/api/models/services/travis.py, lifemonitor/config.py
Fix missing argument in call to `get_test_build`
=> jenkins - fix call to get_test_build

.github/workflows/docs.yaml, lifemonitor/api/models/__init__.py, lifemonitor/api/models/rocrate.py, lifemonitor/api/models/services/__init__.py, lifemonitor/api/models/services/github.py, lifemonitor/api/models/services/jenkins.py, lifemonitor/api/models/services/service.py, lifemonitor/api/models/services/travis.py, lifemonitor/config.py, lifemonitor/test_metadata.py, lifemonitor/utils.py, requirements.txt, specs/api.yaml, tests/config/data/make-test-rocrates.py, tests/config/web/app.py, tests/integration/api/controllers/test_workflows.py, tests/integration/api/services/test_github_service.py, tests/unit/api/models/test_github.py, tests/unit/test_utils.py, tests/utils.py
Opening this PR to collect the implementation of support for GitHub Actions.  When complete will solve issue #104
=> Support for GitHub Actions as testing service

lifemonitor/api/models/services/github.py
This PR works around a change in behaviour to Github's [List Workflow Runs API](https://docs.github.com/en/rest/reference/actions#list-workflow-runs) (maybe due to a problem?  The specification hasn't changed).  The API has a `status` argument which we used to filter the runs that are retrieved to only the ones with the status that interests us.  This worked in the past, but as of 2021/06/23 the relevant Github API started returning only the latest three matching runs when we specify that argument.
This PR works around this problem by retrieving all runs and then filtering them in our code.
=> Work around Github returning only last three with specific status

lm_admin_guide.md, restish-cli-register-workflow.md, restish-cli.md
This PR adds a new page showing how to register an RO-crate from using Restish and then query some of the APIs.
=> Added docs on registering and querying from CLI

lifemonitor/api/__init__.py, lifemonitor/api/models/services/github.py, lifemonitor/api/models/services/jenkins.py, lifemonitor/api/models/services/service.py, lifemonitor/api/models/services/travis.py, lifemonitor/auth/models.py, lifemonitor/auth/oauth2/client/models.py, lifemonitor/auth/oauth2/client/providers/github.py, tests/unit/api/models/test_travis.py, tests/unit/api/models/test_workflow_status.py
This PR allows LifeMonitor to interact with Github API using OAuth tokens.
=> Feature/enable user authentication on GitHub testing service

lm_admin_guide.md
This PR adds some documentation on how to upgrade an existing LifeMonitor deployment
(addresses https://github.com/crs4/life_monitor/pull/133#issuecomment-911731692).
=> Add section "How to upgrade"

lifemonitor/api/models/services/github.py, specs/api.yaml, tests/integration/api/controllers/test_instances.py
This PR definitively removes the deprecated endpoint to retrieve build logs
=> Disable logs endpoint

lifemonitor/auth/templates/auth/apikeys_tab.j2
Fixes the help text in the API keys tab
=> Fix text in the API keys tab

docker/lifemonitor.Dockerfile, requirements.txt
This PR updates the two main frameworks (Flask and connexion) and other minor libraries on which LifeMonitor depends
=> Migration to Flask 2

web-app.md
Updates the ro-crate creation guide according to the latest changes in ro-crate-py, which allow to simplify the syntax.
=> Update ro-crate-py CLI instructions to the latest release

lifemonitor/api/models/registries/__init__.py, lifemonitor/api/models/registries/forms.py, lifemonitor/api/models/registries/registry.py, lifemonitor/api/models/registries/settings.py, lifemonitor/api/models/repositories/config.py, lifemonitor/api/models/wizards/__init__.py, lifemonitor/api/models/wizards/repository_template.py, lifemonitor/api/serializers.py, lifemonitor/auth/__init__.py, lifemonitor/auth/controllers.py, lifemonitor/auth/models.py, lifemonitor/auth/oauth2/client/models.py, lifemonitor/auth/templates/auth/github_settings.j2, lifemonitor/auth/templates/auth/profile.j2, lifemonitor/auth/templates/auth/registry_settings.j2, lifemonitor/integrations/github/__init__.py, lifemonitor/integrations/github/app.py, lifemonitor/integrations/github/controllers.py, lifemonitor/integrations/github/events.py, lifemonitor/integrations/github/forms.py, lifemonitor/integrations/github/registry.py, lifemonitor/integrations/github/services.py, lifemonitor/integrations/github/utils.py, migrations/versions/770508273f01_add_client_name_property_on_.py, migrations/versions/bb0a4c003e28_add_githubworkflowregistry.py, specs/api.yaml
Relevant changes:
* move *Registry Integration* settings to a dedicated tab
* serialise name (long format) and identifier of workflow registries:
```json
{
"uuid": "aa16c6a9-571f-4a62-976f-60ea514ad2c1",
"identifier": "workflowhub_dev",
"name": "WorkflowHub Dev",
"type": "seek",
"uri": "https://dev.workflowhub.eu/"
}
```
* minor bug fixes
=> Update registry settings

lifemonitor/api/models/__init__.py, lifemonitor/api/models/issues/common/files/properties.py, lifemonitor/api/models/registries/__init__.py, lifemonitor/api/models/registries/registry.py, lifemonitor/api/models/repositories/config.py, lifemonitor/api/models/repositories/files.py, lifemonitor/api/models/repositories/github.py, lifemonitor/api/models/repositories/templates.py, lifemonitor/api/models/wizards/__init__.py, lifemonitor/api/models/wizards/repository_template.py, lifemonitor/auth/oauth2/client/models.py, lifemonitor/integrations/github/app.py, lifemonitor/integrations/github/controllers.py, lifemonitor/integrations/github/events.py, lifemonitor/integrations/github/services.py, lifemonitor/integrations/github/utils.py, lifemonitor/templates/repositories/base/lifemonitor.yaml.j2, lifemonitor/utils.py
* activate GitHub App immediately after installation
* appropriately handle "branch creation" event
* detect missing workflow name
* minor changes on repo templates
* fix registry token update
* fix cleanup of support branches
=> Fix/various GitHub App issues

workflow_testing_ro_crate.md
Adds documentation on LM-supported test service types to the Workflow Testing RO-Crate spec.
=> Workflow Testing RO-Crate: add guidance on setting up TestInstance for LM

.github/workflows/docs.yaml, .github/workflows/main.yaml, Makefile, docker/lifemonitor.Dockerfile, lifemonitor/__init__.py, lifemonitor/api/models/repositories/base.py, lifemonitor/api/models/repositories/github.py, lifemonitor/api/models/rocrate/generators.py, requirements.txt, tests/unit/auth/models/test_tokens.py
* Fix deprecated version of some base GitHub Actions on CI pipelines
* Avoid CI builds when some paths are updated
=> Fix/Update CI GitHub Actions

lifemonitor/api/serializers.py, specs/api.yaml
=> feature/include issue description with API issues list

lifemonitor/integrations/github/issues.py
Update Issue/PR description with the originating LM IssueID
fix #256
=> Include LM IssueID on GitHub Issues/PRs

lifemonitor/app.py, lifemonitor/auth/controllers.py, lifemonitor/auth/oauth2/client/controllers.py, lifemonitor/auth/oauth2/server/templates/authorize.html, lifemonitor/auth/templates/auth/github_settings.j2, lifemonitor/auth/templates/auth/identity_not_found.j2, lifemonitor/auth/templates/auth/login.j2, lifemonitor/auth/templates/auth/merge.j2, lifemonitor/auth/templates/auth/notifications.j2, lifemonitor/auth/templates/auth/profile.j2, lifemonitor/auth/templates/auth/register.j2, lifemonitor/auth/templates/auth/registry_settings.j2, lifemonitor/auth/templates/auth/set_password.j2, lifemonitor/config.py, lifemonitor/integrations/github/templates/github_integration/registration.j2, lifemonitor/mail.py, lifemonitor/templates/api/issues.j2, lifemonitor/templates/base.j2, lifemonitor/templates/macros.j2, requirements.txt
Maintenance PR:
* upgrade dependencies to fix security issues and resolve some deprecations;
* set `/account` as prefix of all the endpoints to manage user settings
=> refactor: minor updates of auth module

lifemonitor/api/models/issues/general/lm.py, lifemonitor/api/models/issues/general/metadata.py, lifemonitor/api/models/issues/general/repo_layout.py
This PR changes the labels attached to the issues created by LifeMonitor
=> Review issue labels

lifemonitor/api/models/services/github.py, lifemonitor/integrations/github/utils.py, lifemonitor/utils.py, tests/unit/api/models/test_github.py, tests/unit/cache/test_cache.py, tests/unit/test_utils.py, tests/utils.py
This PR fixes several issues that prevent builds to be properly refreshed.
=> Fix/issues with GitHub builds

lifemonitor/integrations/github/issues.py, lifemonitor/integrations/github/utils.py
=> Remove bot lm shorthand

lifemonitor/api/models/rocrate/generators.py
=> Update comment to generate_crate cfg

lifemonitor/api/models/repositories/files/base.py
=> fix: cache repo content read from file

requirements.txt
=> build(deps): bump cryptography and PyYAML

lm_wft_best_practices_github_app.md
=> docs: Document config file schema and link to validator.

lifemonitor/auth/controllers.py, lifemonitor/auth/oauth2/client/models.py, lifemonitor/auth/oauth2/client/providers/__init__.py, lifemonitor/auth/oauth2/client/providers/github.py, lifemonitor/auth/oauth2/client/providers/lsaai.py, lifemonitor/auth/oauth2/client/providers/seek.py, lifemonitor/auth/templates/auth/account_tab.j2
This PR addresses the issue https://github.com/crs4/life_monitor/issues/313
=> feat: link connected account IDs to profile page on IdP service

lifemonitor/integrations/github/controllers.py, lifemonitor/integrations/github/services.py
This pull request enables the GitHub App to submit the workflow registration even when the release tag is created by a GitHub user who doesn't have an account on LifeMonitor. The workflow submitter in WorkflowHub and LifeMonitor will be the user registered on LifeMonitor who first triggered the workflow registration.
=> feat: extend automatic workflow registration to all members of the GH organisation
