crs4/life_monitor

- README.md
Clarify that the lifemonitor image needs a populated `certs` directory.
> Readme note on certificates

- README.md
Adds a walkthrough on setting up WorkflowHub + LifeMonitor with OAuth enabled on a single physical host.
> Oauth setup docs

- interaction_experiments/check_cwl.py
- interaction_experiments/check_galaxy.py
- lifemonitor/ro_crate.py
Updates the code for interacting with RO-Crates to support both the upcoming RO-Crate 1.1 release and the now-current-soon-legacy RO-Crate 1.0. At the moment, WorkflowHub is generating 1.1 crates for workflows uploaded as single files, but legacy 1.0 crates are still around (e.g., from old crate uploads) and probably will be for a while even after the official release of RO-Crate 1.1.
The code has been moved from the workflow check example scripts to an `ro_crate` module. Once [ro-crate-py](https://github.com/ResearchObject/ro-crate-py) is stable enough, we should be able to use that instead.
> Update RO-Crate-related code

- lifemonitor/test_metadata.py
- requirements.txt
See https://github.com/ResearchObject/ro-crate-py/pull/55 and the [corresponding changes in the test metadata spec](https://github.com/crs4/life_monitor/wiki/Workflow-Testing-RO-Crate/_compare/a620721598ed65749c95ba8aeadbddb31e50f328...29d1ed97ebd35ab26f8f151e4799e02b3bb0ad58).
For now, only the `test_metadata` module has been changed (allowing to support the new format). RO-Crate metadata files in tests and examples have not been changed (the new ro-crate-py version supports the previous way of referencing suites from a `test` dir).
> Update test_metadata module according to the latest test spec

- lifemonitor/test_metadata.py
There is no special "test" dir in the current testing crate spec, and testing material could be anywhere in the crate. I forgot to address this in #79.
> Fix handling of test definition from ro-crates

- index.md
- workflow_testing_ro_crate.md
Adds the Workflow Testing RO-Crate spec, ported [from the wiki](https://github.com/crs4/life_monitor/wiki/Workflow-Testing-RO-Crate). After merging this, the wiki page's content will be replaced with a reference to the web site page.
> Workflow Testing RO-Crate docs from the wiki

- assets/css/style.scss
This PR overrides the template's static column widths so that the layout of the page can use the full width of the browser
> Override static width settings

- lifemonitor/exceptions.py
- tests/unit/api/controllers/test_workflows.py
Bad requests were resulting in unhandled server side exceptions and consequently HTTP 500 status responses.
This PR adds a handler for `connexion.ProblemException`, thus resulting in the proper propagation of errors reported from the connexion framework.
> Fix response to failure in request validation

- lifemonitor/api/controllers.py
- specs/api.yaml
- tests/integration/api/controllers/test_users.py
- tests/integration/api/controllers/test_workflows.py
- tests/unit/api/controllers/test_suites.py
- tests/unit/api/controllers/test_workflows.py
A user may register a workflow that is not registered elsewhere, and thus does not have a pre-assigned id.  With this PR, for such workflows LM will dynamically generate a UUID and return it to the caller.
> Accept a workflow without an id 

- lifemonitor/auth/serializers.py
- tests/unit/auth/models/test_users.py
The fix was implemented at the serialization layer, returning a
spec-compliant LifeMonitor identity.
> Fix call to show_current_user_profile with local users

- lifemonitor/api/controllers.py
- lifemonitor/api/models/services/service.py
- lifemonitor/api/serializers.py
- lifemonitor/exceptions.py
- specs/api.yaml
- tests/unit/api/controllers/test_instances.py
This PR removes the last_logs property from the BuildSummary schema, addressing issue #94.  It also includes some other small things, and in particular a fix to the exception handling code in `lifemonitor.api.controllers.workflows_delete` and `lifemonitor.api.controllers.instances_delete_by_id`.
> Remove last_logs from build summaries

- docker/lifemonitor.Dockerfile
- examples/1_WorkflowRegistrySetup.ipynb
- examples/2_WorkflowRegistryAuthorize.ipynb
- examples/3_WorkflowRegistryUsers.ipynb
- examples/4_WorkflowRegistryWorkflows.ipynb
- lifemonitor/api/controllers.py
- specs/api.yaml
- tests/integration/api/controllers/test_registries.py
- tests/integration/api/controllers/test_users.py
- tests/integration/api/controllers/test_workflows.py
- tests/integration/api/services/test_github_service.py
- tests/integration/api/services/test_services.py
- tests/unit/api/controllers/test_workflows.py
This PR adds specifications for the successful (i.e., http 201) responses returned from calls registering workflows:
* POST /registries/current/workflows
* POST /registries/{registry_uuid}/workflows
* POST /users/{user_id}/workflows
* POST /users/current/workflows
For homogeneity, the responses reuse the already-defined `Workflow` schema.  However, this schema defines the same properties as the original responses **but** calls the workflow uuid `uuid` instead of `wf_uuid`.  Thus, this PR introduces an incompatible change in the API in that the responses to the above-listed POST call contain a `uuid` property instead of `wf_uuid`.  The schema also adds the workflow `name` to the response.
The PR also defines as **required** the following schema properties:
* WorkflowStatus
- …
> Add specification responses from posting workflows

- lifemonitor/api/models/services/github.py
- lifemonitor/api/models/services/jenkins.py
- lifemonitor/api/models/services/service.py
- lifemonitor/api/models/services/travis.py
- lifemonitor/api/models/testsuites/testbuild.py
- lifemonitor/api/models/testsuites/testinstance.py
- lifemonitor/api/serializers.py
- lifemonitor/serializers.py
- specs/api.yaml
This PR extends the API specs and implementation with the `links.origin` property that links `TestInstances` and `TestBuilds` registered on LM to the corresponding entities on the actual testing services (Travis, Github, Jenkins). 
`TestBuild` example:
```javascript
{
build_id: 167444,
suite_uuid: "e3208b02-69b6-4e32-a3dc-b93967d30e2c",
status: "passed",
....,
timestamp: 1616427012,
duration: 2648,
links: {
origin: "https://github.com/crs4/life_monitor/actions/runs/968650807"
}
}
```
> Expose links to TestingServices

- tests/config/registries/seek/seek.Dockerfile
The seek image used for testing should be executable by any user id.  This PR sets the entrypoint permissions to 755.  It seems this is sufficient to let any user start it.
> Set exec permissions on seek image entrypoint

- restish-cli-register-workflow.md
Adds a short section on how to delete a workflow to the Restish wf reg example.
> Docs: show how to delete a workflow in the Restish example

- interaction_experiments/check_galaxy.py
- interaction_experiments/data/crates/ro-crate-cwl-basefreqsum/ro-crate-metadata.json
- interaction_experiments/data/crates/ro-crate-galaxy-sortchangecase/ro-crate-metadata.json
- interaction_experiments/requirements.txt
- interaction_experiments/workflow_examples/galaxy/sort-and-change-case/test_on_docker_galaxy.sh
- requirements.txt
Bumps ro-crate-py to 0.5.1, which contains [critical bug fixes](https://github.com/ResearchObject/ro-crate-py/pull/100) to support recent RO-Crates from WorkflowHub.
> Bump ro-crate-py version

- k8s/Chart.lock
- k8s/Chart.yaml
- k8s/pvc-backend-data.yaml
- k8s/templates/_helpers.tpl
- k8s/templates/job-init.yaml
- k8s/values.yaml
This PR introduces minor updates and bug fixes to support back-end v0.5.0:
* adds PVC to store workflows
* updates labels of the init job to fix an issue with `helm upgrade`
> Update chart to 0.5.0

- lifemonitor/test_metadata.py
- tests/conftest.py
- tests/unit/test_read_crate.py
Fixes a potential problem with the retrieval of test instances -- the current code assumes that the `instance` property of a `TestSuite` entity has a list as its value, but if there's only one it's perfectly legal to just write:
```json
"instance": {"@id": "#instance_id"}
```
I've also added a new test to check the fix.
> Add tests for RO-Crate reader

- lifemonitor/test_metadata.py
- tests/unit/test_read_crate.py
* Remove obsolete code
* Add a function to get the workflow's authors
The idea is that the latter will be used to display the workflow's authors in the web app. Example output:
```python
[
{
"name": "Josiah Carberry",
"url": "https://orcid.org/0000-0002-1825-0097"
},
{
"name": mickeymouse,
"url": None
}
]
```
When available, the value of the "url" field can be used to link to the author's page.
> Update test metadata

- lifemonitor/auth/models.py
- lifemonitor/integrations/github/controllers.py
- lifemonitor/integrations/github/notifications.py
- lifemonitor/integrations/github/services.py
- lifemonitor/mail.py
- lifemonitor/templates/mail/github_workflow_version_notification.j2
- lifemonitor/templates/repositories/base/lifemonitor.yaml.j2
Allow Github app to notify users when a workflow version has been created/updated/deleted.
* Notifications are enabled by default, but they can be turned off per branch/tag through the `lifemonitor.yaml` configuration file:
```yaml
...
push:
branches:
- name: "main"
update_registries: []
enable_notifications: false
- name: "develop"
update_registries: []
tags:
- name: "*.*.*"
update_registries: [wfhubdev]
enable_notifications: true
```
* Notifications are sent via email if email notifications are enabled:
> Feature/enable Github app notifications

- lifemonitor/api/models/wizards/repository_template.py
Fixes a few typos in the messages sent by `RepositoryTemplateWizard`
> Fix typos in the repository template wizard

- k8s/templates/secret.yaml
- k8s/values.yaml
- lifemonitor/api/models/repositories/config.py
- lifemonitor/app.py
- lifemonitor/config.py
- lifemonitor/integrations/github/controllers.py
- lifemonitor/integrations/github/settings.py
- lifemonitor/integrations/github/utils.py
- lifemonitor/templates/repositories/base/lifemonitor.yaml.j2
- lifemonitor/utils.py
- settings.conf
- tests/unit/auth/models/test_tokens.py
This PR allows to use the same GitHub app setup with multiple LifeMonitor instances.
Every LifeMonitor instance acts as a proxy for the other instances connected to the same GitHub app configuration.
The `lifemonitor.yaml` configuration file allows users to choose which LifeMonitor instance should handle which branch or tag.
> Feature/GitHub app with multiple LM instances

- lifemonitor/cache.py
- lifemonitor/integrations/github/controllers.py
- lifemonitor/integrations/github/settings.py
- lifemonitor/integrations/github/templates/github_integration/registration.j2
- lifemonitor/tasks/jobs/github.py
This PR introduces a new callback endpoint for the LifeMonitor GitHub App. 
The endpoint provides:
* a feedback to confirm that the installation was successful;
* an overview of the user's repos where the GitHub App has been installed (with a link to easily jump to those repos on GitHub);
* three additional control buttons to jump to the LifeMonitor *Dashboard*, to the *GitHub App Global Settings* and to the App *administration page on GitHub* (to add/remove repos to the current installation or to completely uninstall the app from the user account.
By clicking the **Manage** button the user will be redirected to the GitHub app administration page:
(fix #253, #254)
> feature/improve GitHub App installation

- cli/client/issues.py
- lifemonitor/api/models/issues/__init__.py
- lifemonitor/api/models/issues/general/experimental.py
- lifemonitor/api/models/issues/general/lm.py
- lifemonitor/api/models/issues/general/metadata.py
- lifemonitor/api/models/issues/general/repo_layout.py
- lifemonitor/api/models/repositories/templates/__init__.py
- lifemonitor/api/models/wizards/repository_template.py
- lifemonitor/utils.py
- tests/unit/issues/test_missing_workflow.py
- tests/unit/issues/test_rocrate_metadata.py
This PR proposes a solution for issue #246 by reorganizing automated repository check implementations into new modules.  The idea is to split the checks into the following categories:
* general.lm: things specific to LifeMonitor 
* general.metadata: metadata-related checks (e.g., RO-crate properties)
* general.repo_layout: general repository layout issues, such as missing metadata files or workflow files
* <one category per supported workflow type -- e.g., galaxy, snakemake)>
The `lifemonitor/api/models/issues` directory therefore takes the form:
```
./galaxy
./snakemake
./general
./general/metadata.py
./general/repo_layout.py
./general/experimental.py
./general/lm.py
./__init__.py
```
The PR changes the generation of check identifiers to use the module+class name rather than converting …
> Reorganize repository check modules

- lifemonitor/api/serializers.py
- lifemonitor/static/src/package.json
- specs/api.yaml
- tests/integration/api/controllers/test_suites.py
- tests/unit/api/controllers/test_suites.py
* fix serialisation of the workflow `status` property nested in the `/workflows` response. The old implementation returns only the latest build instead of all the "latest builds" (i.e., the latest build of each test instance of each test suite)
* rename `status` property of test suite to `aggregate_test_status`
> update serialisation of {workflow, suite} status property 

- cli/client/issues.py
- cli/client/utils.py
- lifemonitor/api/models/issues/__init__.py
- lifemonitor/api/models/issues/general/metadata.py
- lifemonitor/api/models/issues/general/repo_layout.py
- lifemonitor/api/models/repositories/base.py
- lifemonitor/api/models/repositories/config.py
- lifemonitor/api/models/repositories/files/templates.py
- lifemonitor/api/models/repositories/files/workflows/__init__.py
- lifemonitor/templates/repositories/base/.lifemonitor.yaml.j2
This PR makes some changes to the CLI path for executing issue checks. It fixes some small problems which kept the functionality from running. It also avoids failing fast, so that multiple unrelated checks can be executed in the same run. Finally, it includes some small fixes to type hints.
> fix CLI to execute issue checks

- lifemonitor/api/models/issues/general/metadata.py
Fixes the MissingWorkflowName check so that it verifies that the repository configuration object exists before checking for a workflow name.
> Fix access to missing repo configuration

- utils/certs/gencerts.sh
`ifconfig` is obsolete.  This PR introduces a fallback to using `ip addr` to get the list of IPs for the certificates generated by the gencerts.sh utility.
> Support generating IP list with `ip addr`

- Makefile
The various `start*` Makefile targets start docker-compose definitions which mount files or directories in Docker containers.  These mounts don't work as expected if the files have strict permissions.
This PR adds a Makefile target that sets world-readable permissions for the relevant files.
Note:  The branch for this PR is based on the branch fix/missing-ifconfig (PR #332).  Merge that one first.
> fixup: set file permissions in Makefile targets

- lifemonitor/utils.py
This PR corrects the name of the configuration variable used to set the connection timeout used when contacting external services.
> fix: correct config variable used for timeout of service connections

- requirements.txt
Downgrade `SQLAlchemy` to **1.4.41** to fix a conflict with `sqlmodel 0.8.0`, which requires SQLAlchemy  <= **1.4.41**.
> build(pip): pin SQLAlchemy to 1.4.41

- specs/api.yaml
> fix: Document that roc_link in API can point to a GitHub repository

- k8s/Chart.yaml
- lifemonitor/static/src/package.json
- requirements.txt
- specs/api.yaml
* close https://github.com/crs4/life_monitor/pull/351
* close https://github.com/crs4/life_monitor/pull/350
> build(deps): v0.11.4 security updates

- lifemonitor/api/models/issues/general/lm.py
- lifemonitor/api/models/issues/general/repo_layout.py
- lifemonitor/api/models/repositories/local.py
- lifemonitor/utils.py
This PR adds a new check to verify whether the workflow repository contains at least one branch.
[fix #255]: the check takes precedence over all others, so the scenario described in 255 should no longer occur.
> feat: check for the presence of at least one branch

- lifemonitor/api/models/repositories/github.py
- lifemonitor/api/models/workflows.py
- lifemonitor/integrations/github/controllers.py
- lifemonitor/integrations/github/events.py
- lifemonitor/integrations/github/services.py
This PR fixes the identification of the LifeMonitor user to be used for submitting workflows on LifeMonitor, starting from an update of the corresponding workflow repository on a Github organisation.
> fix: improve identification of workflow submitter
